base_request_handler:
  timeout: 60
  default_method: GET
  user_agent: >-
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)
    AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/90.0.4430.85 Safari/537.36
